---
- hosts: dev
  become: yes
  vars:
    pkgs:
      - git
      - tomcat
      - rpm
  tasks:
  - name: install various packages using variables concept
    yum:
      name: "{{ pkgs }}"
      state: present